### ISSUE TITLE
Distribution of navigational commands in the full dataset

### ISSUE THREAD

**Issue by ap229997** [bradyz/2020_CARLA_challenge#9]
The distribution of the navigational commands in the full dataset (# images for each command) is severely skewed towards command '4'. Is this due to the autopilot or the 76 routes provided in ```leaderboard/data/routes_*.xml```?
![carla_9](https://user-images.githubusercontent.com/19525041/85991003-25c3c580-b9f3-11ea-807a-716b43342bec.png)

**Comment by bradyz** [comment]
This is due to the preset routes. Most of the time is simply lane following (which I have merged with straight)

**Comment by ap229997** [comment]
Training the MapAgent on this data would probably result in a very biased agent that would perform poorly at turns and lane changes?

**Comment by bradyz** [comment]
in our experiments, we've seen the map agent to do quite well due to the nice representation of the map

the image agent, if trained naively, fails in the ways you mentioned
to do better across all navigational commands, we use the all-branches supervision from LBC, which acts as a sort of nice sampling

note: in this repo, we don't condition on discrete actions, but actually render a sort of "command heatmap" that you can see in the readme. I found these to work better in the CARLA challenge

**Comment by ap229997** [comment]
Thanks for the clarification.
